spring: 
  application:
    name: prototipo
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:prototipo;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password: sa
    driverClassName: org.h2.Driver    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: create
  main:
    allow-bean-definition-overriding: true      
security:
  oauth2:
    client:
      clientId: ssaoauth
      clientSecret: $2a$10$ckYQSEPVEh/CZZJvoA5XU.JXjSNfhYTJjlVSuQ4HLn5/VbM195BnW
      grant-type: client_credentials
      scope: server
      access-token-uri: http://integra2.ico.red:12011/nassa/oauth/token
    resource:
      token-info-uri: http://integra2.ico.red:12011/nassa/oauth/check_token
server:
  port: 8081
  servlet:
    context-path: /prototipo      
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: INFO
        type: 
           descriptor:
              sql: TRACE 
connection:
  jndiName: es/ico/dsPrototipo
cors:
  allowed-origins:
    - http://127.0.0.1:7001
    - http://127.0.0.1:4200
    - http://localhost:7001
    - http://localhost:4200
    - http://integra2.ico.red
    - http://integra2.ico.red:7031
    - http://prepro1.ico.red
    - http://prepro1.ico.red:7031
    - http://prepro.ico.red
    - http://sun1.ico.red
    - http://sun2.ico.red
