spring: 
   h2:
    console:
      enabled: true
      path: /console
   datasource:
    url: jdbc:h2:file:~/entityA
    username: sa
    password: sa
    driverClassName: org.h2.Driver
   jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
    generate-ddl: true
    hibernate:
      ddl-auto: create
security:
    oauth2:
      resource:
        tokenInfoUri: http://localhost:8090/oauth/check_token
      client:
        client-id: web
        client-secret: pass
server:
  port: ${SERVER_PORT:8081}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    hostname: micro-entity-a
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health
